# Cloud Build 設定ファイル
# 目的：GitHub リポジトリの push → Cloud Build が自動実行
#       → Docker イメージをビルド → Container Registry に保存
#       → Cloud Run にデプロイ

steps:
  # ステップ1: Docker イメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    id: build_image
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/actask-unified:latest"
      - "-t"
      - "gcr.io/$PROJECT_ID/actask-unified:$COMMIT_SHA"
      - "-f"
      - "./ACTASK-app/Dockerfile"
      - "./ACTASK-app"
    waitFor: ["-"]

  # ステップ2: イメージを Container Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    id: push_image
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/actask-unified:$COMMIT_SHA" # COMMIT_SHAタグでプッシュを推奨
    waitFor: ["build_image"]

  # ステップ3: Cloud Run にデプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy_cloudrun
    args:
      - "run"
      - "deploy"
      - "actask-service" # サービス名を明示的に指定
      - "--image=gcr.io/$PROJECT_ID/actask-unified:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
    waitFor: ["push_image"]

# ビルド後の成果物（推奨）
images:
  - "gcr.io/$PROJECT_ID/actask-unified:latest"
  - "gcr.io/$PROJECT_ID/actask-unified:$COMMIT_SHA"

# タイムアウト（デフォルト: 10分）
timeout: "1800s"

# ★★★ 修正箇所: ロギング設定を追加 ★★★
options:
  # カスタムサービスアカウント使用時の必須設定
  # ログを Cloud Logging にのみ保存するように指定します
  logging: CLOUD_LOGGING_ONLY
# ★★★ ------------------------------ ★★★

substitutions:
  _REGION: "us-central1"
  _SERVICE_NAME: "ACTASK"
