steps:
  # ビルドステップ：Dockerfile を使用してイメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest"
      - "-f"
      - "api/Dockerfile"
      - "."
    id: "build-image"
    timeout: "1200s"

  # プッシュステップ：ビルドしたイメージをContainer Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"
    id: "push-image"
    timeout: "600s"
    waitFor: ["build-image"]

  # デプロイステップ：Cloud Run にデプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"
      - "--region=$_REGION"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--timeout=3600"
      - "--memory=512Mi"
      - "--cpu=1"
      - "--set-env-vars=PORT=8080,API_BASE_URL=https://$_SERVICE_NAME-764158189667.asia-northeast1.run.app"
    id: "deploy-cloud-run"
    waitFor: ["push-image"]
    timeout: "900s"

# イメージ情報
images:
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest"

# ビルド設定
options:
  machineType: "N1_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: "ALLOW_LOOSE"

substitutions:
  _SERVICE_NAME: "actask-app"
  _REGION: "asia-northeast1"

# タイムアウト設定
timeout: "3000s"
